# Generated by Django 3.2.16 on 2023-05-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': ('Подписка',), 'verbose_name_plural': 'Подписки'},
        ),
    ]
